package com.tbox.fotki.util

object Constants {
    const val SHORT_URL = "view_short_url"
    const val STATUS = "status"
    const val ORIGINAL_FILENAME = "original_filname"
    const val INACCESSIBLE = "inaccessible"
    const val VIDEO_CONVERT_STATUS = "video_convert_status"
    const val BASE_URL = "https://api.fotki.com/v3"
    //val BASE_URL = "http://api.dev.fotki.com:8786/v3";
    const val NEW_SESSION = "/new_session?"
    const val LOGIN = "login"
    const val PASSWORD = "password"
    const val GET_ACCOUNT_INFO = "/get_account_info?"
    const val SESSION_ID = "session_id"
    const val GET_ACCOUNT_TREE = "/get_account_tree?"
    const val GET_ALBUM_CONTENT = "/get_album_content?"
    const val CURRENT_PAGE = "current_page"
    const val GET_ALBUM_ITEM_COUNT = "/get_album_items_count?"
    const val CREATE_FOLDER_API = "/create_folder?"
    const val CREATE_FOLDER_NAME = "folder_name"
    const val GET_FOLDER_CONTENT = "/get_folder_content?"
    const val UPDATE_FOLDER = "/update_folder?"
    const val UPDATE_ITEM_NAME = "name"
    const val UPDATE_ALBUM_DESC = "description"
    const val UPDATE_FOLDER_DESC = "descr"
    const val CREATE_ALBUM_API = "/create_album?"
    const val CREATE_ALBUM_NAME = "name"
    const val UPDATE_ALBUM = "/update_album?"
    const val FILE_UPLOAD = "/upload"
    const val GOOGLE_NEW_SESSION = "/google_new_session?os=android"
    const val ACCESS_TOKEN = "access_token"
    const val SOCIAL_MEDIA_LOGIN_KEY = "login"
    const val FACEBOOK_NEW_SESSION = "/facebook_new_session?os=android"
    const val IS_PHOTO_EXISTS = "/file_exists?"
    const val SHA1 = "sha1"
    const val DELETE_MEDIA_API = "/delete_media?"
    const val MEDIA_ID_ENC = "media_id_enc"

    const val GET_FOLDER_CONTENT_R = "get_folder_content"

    //shared preference keys...
    const val SESSION_ID_FILE = "SessionIdFile"
    const val SESSION_ID_KEY = "SessionIdKey"
    const val USER_INFO_FILE = "UerInfoFile"
    const val USER_INFO_USERNAME = "UserName"
    const val USER_INFO_PASSWORD = "UserPassword"
    const val USER_INFO_IS_LOGIN = "IsUserLogin"
    const val SWITCH_TAB_FILE = "switchTabFile"
    const val SWITCH_TAB_STATE = "switchTabState"

    //web response json keys...
    const val DATA = "data"
    const val ACCOUNT_TREE = "account_tree"
    const val PUBLIC_FOLDER = "public"
    const val PRIVATE_FOLDER = "private"
    const val API_MESSAGE = "message"
    const val FOLDER_ID_ENC = "folder_id_enc"
    const val DESCRICTION = "desc"
    const val SHARE_URL = "url"
    const val NUMBER_OF_ALBUMS = "number_of_albums"
    const val NUMBER_OF_FOLDER = "number_of_folders"
    const val FOLDER_NAME = "folder_name"
    const val ALBUM_ID_ENC = "album_id_enc"
    const val ALBUM_NAME = "name"
    const val ALBUMS = "albums"
    const val FOLDERS = "folders"
    const val COVER_PHOTO_URL = "cover_photo_url"
    const val OK = "ok"
    const val ALBUM = "album"
    const val PHOTOS = "photos"
    const val ALBUM_NAME_IN_RESPONSE = "album_name"
    const val ALBUM_DESCRIPTION_IN_RESPONSE = "album_description"
    const val ID = "id"
    const val VIEW_URL = "view_url"
    const val CREATED = "created"
    const val THUMBNAIL_URL = "thumbnail_url"
    const val ORIGINAL_URL = "original_url"
    const val VIDEO_URL = "video_url"
    const val TITTLE = "title"
    const val VIDEO = "video"
    const val GIF = "gif"
    const val ACCOUNT_INFO = "account_info"
    const val AVATAR = "avatar"
    const val DISP_NAME = "disp_name"
    const val URL = "url"
    const val ITEM_COUNT = "items_count"
    const val FOLDER_ID = "folder_id"
    const val ALBUM_ID = "album_id"
    const val ALBUM_PHOTOS_COUNT = "number_of_photos"
    const val ALBUM_VIDEOS_COUNT = "number_of_videos"
    const val ALBUM_SIZE = "size"
    const val ACCOUNTS_FOUND = "accounts_found"
    const val SOCIAL_LOGINS = "logins"
    const val SOCIAL_AVATAR = "avatar_url"
    const val DATE = "date"
    const val UNIX_DATE = "unix_date"
    const val SPACE_USED = "space_used"
    const val SPACE_LIMIT = "space_limit"
    const val ACTIVE = "active"
    const val SUSPENDED = "suspended"
    const val MEMBER_SINCE = "member_since"
    const val ISFOLDER = "isFolder"
    const val ISALBUM = "isAlbum"
    const val DEFTYPE_FILE = "define_type_file"
    const val DEFTYPE= "define_type"
    const val DEFTYPE_KEY_FOLDER = "define_folder"
    const val DEFTYPE_KEY_ALBUM ="define_album"
    const val PREF_ALBUM_ID = "album_ID"
    const val PREF_ALBUM_NAME = "album_name"
    const val PREF_ALBUM_POSITION ="album_position"
    const val CURRENT_LOAD_ITEM = "current_load"
    const val EXISTS = "exists"
    const val SYNC_STARTED = "sync_started"
    const val MISSING = "missing"
    const val EXIST = "exist"

    // Tags
    const val ROOT_FRAGMENT = "root_fragment"
    const val ALBUM_FRAGMENT = "album_fragment"
    const val NEXT_FRAGMENT = "next_fragment"
    const val SWITCH_TAB = "switch_tab"
    // Intent EXTRAS
    const val FILE_LOAD_SPEED = "speed"
    const val FILE_LOAD_SIZE = "load_size"

    const val PARCEABLE_ALBUM = "parace_able_album"
    const val ALBUM_ITEM_COUNT = "album_item_count"
    const val SELECTED_POSITION = "selected_position"
    const val REQUEST_PAGE = "requested_page"
    const val LOCAL_BROADCAST_ALBUM = "broad_cast_album"
    const val VIDEO_URL_LINK = "video_url_link"
    const val UPDATE_CURRENT_PROGRESS = "update_current_progress"
    const val BEING_UPLOADED_STATUS = "uploaded_progess"
    const val FILE_BEING_UPLOADING = "file_being_uploading"
    const val CURRENT_FILE_COUNT = "current_file"
    const val LOG_TEXT = "log"
    const val TOTAL_FILES_TO_UPLOAD = "total_files_count"
    const val UPLOAD_BROADCAST_ALBUM = "upload_data_successfully"
    const val BEING_UPLOADING_FILE_MIMETYPE = "file_mimeType"
    const val ALL_UPLOADS_DONE = "all_files_uploaded"
    const val UPLOAD_STARTED = "uploading_started"
    const val ALBUM_NAME_UPDATED = "album_name_updated_succ"
    const val FOLDER_NAME_UPDATED ="folder_name_updated_succ"
    const val UPDATE_ALBUM_NAME = "updated_album_name"
    const val UPDATE_ALBUM_DESCRIPTION = "update_album_description"
    const val UPDATE_ALBUM_ID = "update_album_name"
    const val NEW_UPLOAD = "newUpload"
    const val PUBLIC_TAB = "public"
    const val PRIVATE_TAB = "private"
    const val UPLOAD_TAB = "update"
    const val UPLOADING_ALBUM_NAME = "albumName"
    const val UPLOADING_IN_PROGRESS = "uploadingInprogress"
    const val SWITCHSCREEN_WHILE_UPLOADING = "switchScreenDuringUpload"
    const val SESSION_EXPIRED = "FOTKI_SESSION_EXPIRED"
    const val SERVICE_ERROR = "service_error"
    const val SERVICE_CANCEL = "service_cancel"
    const val RETRY_API_CALL = "retry_api_call"
    const val FRAGMENTTYPEENUM = "enumFragmentType"
    const val UPLOADINGSTOPPED = "uploading_stopped"
    const val SHARING_FILE_PROGRESS = "sharing_progress"
    const val SHARING_FILE_DOWNLOADED = "sharing_file_downloaded"
    const val SHARING_FILE_ERROR = "sharing_file_downloading_error"
    const val SHARING_FILE_DOWNLOAD_STATUS = "downloading_progress"
    const val DOWNLOAD_STATUS_UPDATED = "status_updated"
    const val UPLOAD_FILE_STATUS = "upload_current_status"
    const val IS_DELETE = "is_delete"
    const val FILE_UPLOADED_LENGTH = "file_uploaded"
    const val SHARING_FILE_DOWNLOADED_SHARE = "sharing_file_downloaded_share"
    // utilies
    const val UTF_8_FORMAT = "utf-8"
    const val FILE_SYNC = "file_sync"

    // action perform
    const val ACTION_UPDATE_ALBUM = "action_updateAlbum"
    const val ACTION_UPLOAD_Files = "action_uploadFiles"
    const val ACTION_UPDATE_FOLDER = "action_updateFolder"
    const val ACTION_CREATE_FOLDER = "action_createFolder"
    const val ACTION_CREATE_ALBUM = "action_createAlbum"
    const val ACTION_RELOAD_FOLDER = "action_reloadFolder"
    const val ACTION_RELOAD_ALBUM = "action_reloadAlbum"

    const val MESSAGE = "message"
    const val SERVICE_MESSAGE = "service_message"
    const val SERVICE_LOG_MESSAGE = "service_log_message"

    // google Android client token for sign UP
    const val GOOGLE_AUTH_KEY_ANDROID = "18819197868-s8pq60u7lf9kcg0eo43ulmu15fkku7ca.apps.googleusercontent.com"
    const val GOOGLE_AUTH_DEBUG_KEY_ANDROID = "18819197868-pc4ha65t3p31nutmu400snvjb8nkvj6s.apps.googleusercontent.com"
    const val GOOGLE_AUTH_KEY_WEB_PRODUCTION = "18819197868-onlh9ev5vtj6de7eaejfsb6f8v41f6el.apps.googleusercontent.com"
}